services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    networks:
      - manages_default
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - manages_default

networks:
  manages_default: